### ISSUE TITLE
hummm，指令没反应.....

### ISSUE THREAD

**Issue by XiaolanX** [Runtus/koishi-plugin-rpixiv#1]

**Comment by Runtus** [comment]
有截图吗？麻烦提供下机器人配置页的截图

**Comment by XiaolanX** [comment]
![image](https://user-images.githubusercontent.com/67143380/236664827-643ec443-2889-4d43-94c3-a312ec561c97.png)
至于控制台....没有任何报错，代理也开了awa
![image](https://user-images.githubusercontent.com/67143380/236664867-74710a4a-81c7-4aee-9e79-76e0f3c770f4.png)

**Comment by XiaolanX** [comment]
G7人私聊是这样的
![image](https://user-images.githubusercontent.com/67143380/236664940-e457c858-c23d-4998-bdc3-88486bee8216.png)

**Comment by Runtus** [comment]
下面代理的isOpen没有打开呀，打开了你的请求才会走代理

**Comment by XiaolanX** [comment]
koishi的全局代理不行吗？

**Comment by Runtus** [comment]
你说的koishi全局代理是指的哪一个？

**Comment by XiaolanX** [comment]
全局设置的代理地址啊awa，
![image](https://user-images.githubusercontent.com/67143380/236665139-0dd6d800-b2de-4e9c-a043-c7c9b40ebbc6.png)
就这个awa

**Comment by Runtus** [comment]
奥，抱歉，我之前没设置过koishi的全局设置。
它这个地方也不是全局代理呀，你看你设置的是本地7891端口的代理，那你只有请求7891端口的时候才会走代理呀

**Comment by XiaolanX** [comment]
是全局吧......？之前用其他插件好像也没问题的样子，而且开了好像也没反应的样子....

**Comment by Runtus** [comment]
抱歉，我可能理解错你的意思了。
你之前说的全局代理在这里没问题，我没用过koishi的这个代理服务器设置，但你这设置的代理服务器是socks代理，而机器人请求走的是http，这样是请求不到那边的数据的

**Comment by XiaolanX** [comment]
啊啊啊抱歉抱歉，我理解错了

**Comment by XiaolanX** [comment]
好像是没反应的样子awa

**Comment by Runtus** [comment]
你试试呢？还有触发的话，两句话放一起才会触发机器人指令，就像下面这样
![image](https://user-images.githubusercontent.com/48038769/236665688-1bf2b4d8-9b39-47a3-ae21-59410cc170f8.png)
我后面会把这个机制改一下，总感觉怪怪的

**Comment by XiaolanX** [comment]
啊.....冒出来了，我还以为是都是单独指令awa

**Comment by Runtus** [comment]
哈哈哈哈，抱歉，这是我设计问题，我之前很早就想优化指令这一块儿的设计的。
最近有些忙，所以这个插件一直就搁置着没怎么改。
