### ISSUE TITLE
出现了未知的错误，请联系管理员

### ISSUE THREAD

**Issue by XiaolanX** [Runtus/koishi-plugin-rpixiv#2]
啊没错又是我awa，控制台依旧没有任何输出，版本是0.1.0来着awa
![QQ图片20230511121202](https://github.com/Runtus/koishi-plugin-rpixiv/assets/67143380/5074430c-9c09-4bb6-b836-a961de81bb33)
![QQ截图20230511121457](https://github.com/Runtus/koishi-plugin-rpixiv/assets/67143380/81d8b968-8a83-4fe5-932d-80808e4c89fa)

**Comment by Runtus** [comment]
你进一下部署koishi后台的日志，打开看看呢

**Comment by XiaolanX** [comment]
不知道为啥插件没有任何输出awa，顺便重新重新发了一次
![image](https://github.com/Runtus/koishi-plugin-rpixiv/assets/67143380/dbb7a717-7edd-450f-98d3-a07ae0201bfc)
![image](https://github.com/Runtus/koishi-plugin-rpixiv/assets/67143380/36a39714-b963-47cd-8aca-8cbc9034019e)

**Comment by Runtus** [comment]
啊，不是这个日志，我想说的是部署koishi环境的日志，因为报错我都是用console.log打印的，这里看不到。例如如果使用docker部署的koishi，就去docker的koishi容器查看

**Comment by XiaolanX** [comment]
CPU烧力（小白），用的是腾讯云的ubuntu，有装桌面就是了awa，日志的话只是启动的终端嘛awa

**Comment by XiaolanX** [comment]
啊，我瞎几把乱整好了awa，抱歉打扰了awa

**Comment by Runtus** [comment]
你是直接在官网上直接下的koishi的linux版的desktop部署的吗

**Comment by XiaolanX** [comment]
emmm，模板吧，yarn create koishi这个指令awa

**Comment by XiaolanX** [comment]
![image](https://github.com/Runtus/koishi-plugin-rpixiv/assets/67143380/39625dce-e589-4edd-81b0-5474d2f23b58)
好像很不稳定的样子，现在又炸了（）

**Comment by Runtus** [comment]
这种情况多半都是网络的问题，你的梯子不稳定，这个issue先开着吧，我后续把日志输出调整到koishi的这个日志面板里。

**Comment by XiaolanX** [comment]
噢噢谢谢awa，我换下梯子吧awa

**Comment by Runtus** [comment]
已添加日志输出功能
