### ISSUE TITLE
koishi desktop，rpixiv插件全部指令均提示“权限不足”

### ISSUE THREAD

**Issue by KiriSuoh** [Runtus/koishi-plugin-rpixiv#7]
看起来很好的功能，想用但用不了。

插件版本0.1.3
在最新版本的koishi desktop环境下，配置好token和代理之后启动，用户明确有kbot提供的5级权限，但无论哪个指令插件都返回“
权限不足”，甚至不产生报错日志。

koishi和系统版本：
System:
    OS: Windows 10 10.0.20348
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz

Binaries:
    Node: 16.19.1
    Yarn: 3.5.0

Koishi:
    Core: 4.14.5
    Console: 5.14.2
    Koishi Desktop: 0.10.6

**Comment by Runtus** [comment]
抱歉，这个插件因为我最近有些忙所以有段时间没维护了，这个问题我今天白天看一下，可能和koishi本身的更新有关，感谢指出问题。

**Comment by Runtus** [comment]
现已修复，等待koishi插件市场更新0.1.4版本即可

**Comment by KiriSuoh** [comment]
好快的回复，感谢！现在权限没问题了，但refreshToken似乎不起作用

已通过推荐的工具获取到了refreshToken
![QQ截图20230917174449](https://github.com/Runtus/koishi-plugin-rpixiv/assets/18628194/d0387844-29b4-47d3-9bed-6a5fb1a012d4)

![QQ截图20230917175131](https://github.com/Runtus/koishi-plugin-rpixiv/assets/18628194/94c3f3e5-3b48-4f89-a8bd-c73b997c5bfe)

![QQ截图20230917174412](https://github.com/Runtus/koishi-plugin-rpixiv/assets/18628194/9af344a8-806b-4679-bc9d-0d4b18dfab4d)

控制台日志
![QQ截图20230917174337](https://github.com/Runtus/koishi-plugin-rpixiv/assets/18628194/ee6a290d-c711-45ae-bdd8-51dd0779b1e4)

**Comment by Runtus** [comment]
<img width="794" alt="image" src="https://github.com/Runtus/koishi-plugin-rpixiv/assets/48038769/9248c37c-f8aa-4c85-897c-945fb5629320">
这里不需要写协议，如果是本地代理，只需要写`localhost`或者`127.0.0.1`即可

**Comment by KiriSuoh** [comment]
原来如此，是我搞错了，现在指令都正常使用了，赞美作者！期待更多功能！
